# =========================================================================
# Base Application Configuration
# =========================================================================
spring.application.name=travel-simulator
spring.profiles.active=dev
